version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ../../:/var/www/html
    environment:
      - CI_ENVIRONMENT=development
      - APP_ENV=dev
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - coaster-net

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ../../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - coaster-net

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data-dev:/data
    networks:
      - coaster-net

networks:
  coaster-net:
    driver: bridge

volumes:
  redis-data-dev:
